spring:
  application:
    name: net-service-netty
  profiles:
    active: dev

netty:
  server:
    port: 8888
    log-level: INFO
    business-thread-pool:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 200
      keep-alive-seconds: 60
      thread-name-prefix: biz-worker-
  client:
    host: localhost
    port: 8888
    heartbeat-interval-seconds: 20
    location-interval-seconds: 5
    reconnect-base-delay-seconds: 1
    reconnect-max-delay-seconds: 120
    terminal-id: "12345678901234"
    manufacturer-id: 1
    license-plate: "京A12345"
